# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit AI Configuration
# This file configures CodeRabbit's automated code review behavior

language: en-US

reviews:
  # Review profile: can be "chill", "assertive", or "balanced"
  profile: balanced
  
  # Generate high-level summary of review findings
  high_level_summary: true
  
  # Enable automatic review assignment to suggested reviewers
  suggested_reviewers: true
  auto_assign_reviewers: true
  
  # Configure automatic reviews for PRs
  auto_review:
    enabled: true
    drafts: false  # Don't review draft PRs
  
  # Finishing touches to add after review
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  
  # Pre-merge checks for PR quality
  pre_merge_checks:
    title:
      mode: error
      requirements: "Title should be concise and descriptive"
    description:
      mode: warning
  
  # Chat integration settings
  chat:
    auto_reply: true
  
  # Integrations with other tools
  integrations:
    jira:
      usage: disabled  # Enable if you use Jira

# Learning settings
knowledge_base:
  learnings:
    scope: global  # Learn from all PRs
  issues:
    scope: global  # Learn from all issues

# Tool configurations
tools:
  # ESLint for JavaScript/TypeScript linting
  eslint:
    enabled: true
  
  # Gitleaks for secret detection
  gitleaks:
    enabled: true
  
  # PMD for Java code quality (if applicable)
  pmd:
    enabled: false
  
  # SwiftLint for Swift code (if applicable)
  swiftlint:
    enabled: false
  
  # golangci-lint for Go code (if applicable)
  golangci-lint:
    enabled: false
  
  # CircleCI configuration validation
  circleci:
    enabled: true
  
  # LanguageTool for grammar and style checking
  languagetool:
    enabled: true
    level: default
  
  # ast-grep for custom code analysis
  ast-grep:
    enabled: true
    essential_rules: true

# GitHub Checks integration
github-checks:
  enabled: true
  timeout_ms: 120000  # 2 minutes timeout